version: '3.4'

services:
    livestreaming:
      image: livestreaming
      build:
        context: .
        dockerfile: ./Dockerfile
      environment:
        NODE_ENV: production
      ports:
        - 80:80
  
  